version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartshop_db
    environment:
      POSTGRES_DB: smartshop
      POSTGRES_USER: smartshop_user
      POSTGRES_PASSWORD: smartshop_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
