# Generated by Django 4.2.7 on 2025-12-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Smartphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="smartphones/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Бренд")),
                ("model", models.CharField(max_length=100, verbose_name="Модель")),
                (
                    "screen_size",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Диагональ экрана"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Оперативная память"
                    ),
                ),
                (
                    "storage",
                    models.CharField(blank=True, max_length=50, verbose_name="Память"),
                ),
                (
                    "battery",
                    models.CharField(blank=True, max_length=50, verbose_name="Батарея"),
                ),
                (
                    "camera",
                    models.CharField(blank=True, max_length=100, verbose_name="Камера"),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Процессор"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Операционная система"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smartphones",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смартфон",
                "verbose_name_plural": "Смартфоны",
                "db_table": "smartphones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="smartphones_slug_36fcd7_idx"),
                    models.Index(
                        fields=["available"], name="smartphones_availab_f047cc_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="smartphones_created_f72a0f_idx"
                    ),
                ],
            },
        ),
    ]
